### PR TITLE
use bootstrap 4 shadows utilities

### PR DESCRIPTION
**Pull request by m5o**
* use bootstrap 4 shadows utilities
  * https://getbootstrap.com/docs/4.1/utilities/shadows/

### CODE REVIEW

**Comment by stefanneculai** [comment]
Just made some changes on the naming to use dash instead of underscore. Could you merge dev and fix the conflicts? Thanks! 🙏

**Comment by stefanneculai** [comment]
It looks there is a merge conflict.

**Comment by stefanneculai** [comment]
@m5o thanks for the work on this, however, we won't go with such big shadows. We're currently in the process of rethinking them a bit and will come with some updates shortly.

**Comment by m5o** [comment]
@stefanneculai My main point is, why support custom shadow utils if bootstrap ships this now by default? 

If you want a decent shadow `.shadow-sm` could be an option to go.

**Comment by stefanneculai** [comment]
We're most likely going to inherit Bootstrap props, but they would be a bit custom. Please have a bit of patience as we're coming with a huge design update in a few days.

**Pull request closed without merging**
