### PR TITLE
Adding RTL Support

### PR DESCRIPTION
**Pull request by anefzaoui**
Hello froala  👋
Froala Design Blocks has got some awesome RTL support already! And since RTL is what I mostly contribute you've left me nothing to give back to you ;)

Here are few things I fixed with RTL support.
Unfortunately some things are still broken, and that's due to Bootstrap's lack of RTL support.
lmk wdyt :)

Cheers,
Ahmed

### CODE REVIEW

**Comment by stefanneculai** [comment]
@anefzaoui Thanks. Could you please rebase this with the `dev` branch?

**Comment by dianaprajescu** [comment]
@anefzaoui we're looking forward to merging your pull request in the `dev` branch. Could you please rebase this?

**Comment by anefzaoui** [comment]
Sorry this must have slipped out of my notifications somehow, sure I'll rebase and push prob a new PR to `dev`!

**Comment by stefanneculai** [comment]
@anefzaoui thanks for this PR. We've launched V2 for the Design Blocks yesterday and there are few changes in the code base. It would be amazing if you could open a new PR with your suggestions and I will make sure they get in shortly.

**Pull request closed without merging**
